[menus]

  [[menus.main]]
    name = 'Ieraksti'
    identifier = 'posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tagi'
    identifier = 'tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
